project:
  type: website
  output-dir: ../docs

website:
  title: "Klimaatatlas"
  search: true
  navbar:
    left:
      - text: "Handleiding"
        href: handleiding.qmd
      - text: "Implementatie Rijnland" 
        href: rijnland.qmd

  sidebar: 

    style: "docked"
    collapse-level: 1
    contents:
      - section: "Gebruikshandleiding"
        collapse: true
        contents:
          - href: gebruikshandleiding/installatie.qmd
            text: "Klimaatatlas installeren"
          - href: gebruikshandleiding/basisgebruik.qmd
            text: "Basisgebruik"
      - section: "Technisch"
        collapse: true
        contents:
          - href: technische_documentatie/configuratiebestand.qmd
            text: "Configuratiebestand"
      - section: "Voorbewerkingen"
        collapse: true
        contents:
          - href: voorbewerkingen/sobek.qmd
            text: "SOBEK exporteren"
      - section: "Nabewerkingen"
        collapse: true
        contents:
          - href: nabewerkingen/arcgis_online.qmd
            text: "ArcGIS online"
      - section: "Implementatie Rijnland"
        collapse: true
        contents:
          - href: rijnland.qmd
            text: "Inleiding"
          - href: rijnland/biomassa.qmd
            text: "Biomassa"

format:
  html:
    theme: cosmo
    css: CSS/custom.css
    toc: true
    include-in-header: header.html
