project:
  type: website
  output-dir: ../docs

website:
  title: "Klimaatatlas"
  navbar:
    left:
      - index.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Tutorial"
        contents:
      - section: "Gebruikershandleiding"
        contents:
          - Gebruikershandleiding/installatie.qmd
      - section: "Technische documentatie"
        contents:
      - section: "Voorbewerkingen"
        contents:
          - href: Voorbewerkingen/sobek.qmd
            text: "SOBEK exporteren"


format:
  html:
    theme: cosmo
    css: CSS/custom.css
    toc: true
    include-in-header: header.html
