project:
  type: website
  output-dir: ../docs

website:
  title: "Klimaatatlas"
  navbar:
    left:
      - index.qmd
  sidebar:
    logo: img/rijnland_logo.jpg
    logo-href: https://www.rijnland.net
    style: "docked"
    search: true
    contents:
      - section: "Tutorial"
        contents:
      - section: "Gebruikershandleiding"
        contents:
          - href: gebruikershandleiding/installatie.qmd
            text: "Klimaatatlas installeren"
          - href: gebruikershandleiding/basisgebruik.qmd
            text: "Basisgebruik"
      - section: "Risicofactoren"
        contents:
          - href: risicofactoren/inleiding.qmd
            text: "Inleiding"
          - href: risicofactoren/biomassa.qmd
            text: "Biomassa"
      - section: "Technische documentatie"
        contents:
          - href: technische_documentatie/configuratiebestand.qmd
            text: "Configuratiebestand"
      - section: "voorbewerkingen"
        contents:
          - href: voorbewerkingen/sobek.qmd
            text: "SOBEK exporteren"
      - section: "Nabewerkingen"
        contents:
          - href: nabewerkingen/arcgis_online.qmd
            text: "ArcGIS online"


format:
  html:
    theme: cosmo
    css: CSS/custom.css
    toc: true
    include-in-header: header.html
