---
title: "Klimaatatlas"
author: "Siebe Bosch"
date: "`r Sys.Date()`"  # This will print the current date
format: html
---

## Inleiding

De klimaatatlas werd ontwikkeld in opdracht van het Hoogheemraadschap van Rijnland. 
Het programma is ontworpen om te identificeren welke regio's en locaties in het beheergebied gevoelig zijn voor slechte waterkwaliteit. 

Denk hierbij aan het risico op: 

* drijflagen
* algen
* zuurstofloosheid
* botulisme
* eutrofiëring

## Toepassing
Dit instrument kan worden gebruikt om in te schatten wat de impact is van klimaatverandering op de waterkwaliteit, maar ook om bij ingrepen in het watersysteem, bijvoorbeeld door nieuwbouwprojecten, te bepalen of aanvullende maatregelen nodig zijn om een goede waterkwaliteit te kunnen (blijven) garanderen. 
Hiermee sluit het Hoogheemraadschap van Rijnland aan op De Nieuwe Omgevingswet, die op 1 januari 2024 is ingegaan.

## Werkwijze
Invoer is een watervlakkenkaart in Geopackage-formaat.

In een JSON-bestand definieert de gebruiker vervolgens zogeheten 'maatlatten' waarvan het resultaat altijd tussen 0 (geen risico) en 1 (maximaal risico) ligt. Voorbeeld voor een maatlat is de invloed van de watertemperatuur op algengroei. Onder 15 graden celcius is algengroei nihil (waarde 0), bij 27 graden is algengroei maximaal (waarde 1) en boven 27 graden loopt de algengroei weer terug. Bij 35 graden is het risico weer terug op 0.

Enkele voorbeelden van maatlatten voor algengroei:

* waterdiepte: geringe waterdiepte = hoog risico; grote waterdiepte = klein risico
* doodlopendheid watergang: doodlopend = hoog risico; vrij doorstromend = klein risico
* fractie riooloverstort: groot aandeel overstortwater = hoog risico; klein aandeel = klein risico

Voor elke waterkwaliteitsgrootheid kan de gebruiker één of meerdere maatlatten combineren. Iedere maatlat krijgt daarbij zijn eigen weegfactor mee. Bijvoorbeeld: watertemperatuur weegfactor 3; doodlopendheid watergang weegfactor 1.

Het Geopackage-bestand wordt samen met het json-bestand ingevoerd in de desktopapplicatie 'Klimaatatlas'. Het resultaat van de berekening wordt weer weggeschreven naar de geopackage en bestaat voor ieder watervlak en grootheid uit een risicowaarde die altijd tussen 0 en 1 ligt. Dit risico kan op een kaart worden getoond en de totstandkoming van het risicogetal kan altijd worden herleid naar de bijdrage van de individuele maatlatten.


## Architectuur
De software bestaat uit een verzameling aan tools en scripts. 
In deze handleiding leggen we de werking ervan uit en werken we een aantal workflows uit waarmee het risico op slechte waterkwaliteit in kaart kan worden gebracht.

* Klimaatatlas: dit is de desktopapplicatie die voor ieder watervlak en waterkwaliteitsgrootheid het risicogetal berekent en wegschrijft
* HydroToolbox: een externe desktopapplicatie van Hydroconsult waarmee waterkwaliteitsresultaten uit SOEK kunnen worden vertaald naar input voor de klimaatatlas.
* Geopackage: een GIS-bestand met watervlakken
* .json-bestand: een tekstbestand waarin de gebruiker de maatlatten definieert. Samen met de geopackage vormt dit bestand de input voor het programma 'Klimaatatlas'.

Het rekenresultaat wordt weer weggeschreven naar de geopackage. Dit bestand kan verder worden gebruikt voor visualisatie, presentatie en analyse.
