---
title: "Risicofactor biomassa"
author: "Siebe Bosch"
date: "`r Sys.Date()`"  # This will print the current date
format: html
---

## Inleiding

De risicofactor 'biomassa' beschrijft de hoeveelheid algen die zich in de waterkolom kunnen bevinden. Hoe meer algen, hoe slechter de waterkwaliteit.

## Maatlatten

Voor 'biomassa' hebben we de volgende maatlatten onderscheiden:

### Overschrijdingstemperatuur

De gedachte achter overschrijdingstemperatuur als maatlat is dat er een temperatuur is waarbij algen maximaal groeien. Deze temperatuur ligt rond de 30 graden celcius. Bij 15 graden of lager is de algengroei minimaal, en ook boven de 45 graden komt hij tot stilstand.

Als parameter nemen we de 'de watertemperatuur die gemiddeld één week per jaar wordt overschreden'. Deze temperatuur verschilt per waterlichaam. Voor dieper water zal de waarde lager liggen dan voor ondiepe sloten. In de voorbewerking hebben we voor ieder waterlichaam deze overschijdingstemperatuur Tex bepaald, als functie van de waterdiepte. 

Het risicogetal van deze maatlat wordt berekend op basis van lineaire interpolatie tussen de volgende drie getalsparen:

* 15 graden: risicogetal 0
* 30 graden: risicogetal 1
* 45 graden: risicogetal 0

Als wegingsfactor voor de maatlat 'Overschrijdingstemperatuur' hanteren we de waarde 1.

### Vermesting stikstof

De aanwezigheid van nutriënten in de waterkolom vormen de drijvende kracht achter de groei van algen. Daarom hebben we ook de vermesting met stikstof meegenomen als maatlat. Als invoerparameter voor deze maatlat nemen we de 50-percentielwaarde van de stikstofconcentratie Nt uit het SOBEK-model van het hoogheemraadschap. Middels een uitgebreide voorbewerking hebben we deze concentraties weten te vertalen naar waarden in de watervlakkenkaart.

Het risicogetal van deze maatlat wordt berekend op basis van lineaire interpolatie tussen de volgende twee getalsparen:

* 0 mg/l: risicogetal 0
* 15 mg/l: risicogetal 1

Als wegingsfactor voor de maatlat 'Vermesting met stikstof' hanteren we de waarde 0.5 omdat er ook nog vermesting met fosfor bij komt.

### Vermesting fosfor

Ook de aanwezigheid van fosfor in de waterkolom veroorzaakt groei van algen. Net als bij stikstof nemen we vermesting met fosfor mee als maatlat. Invoerparameter is de 50-percentielwaarde van de fosforconcentratie Pt uit het SOBEK-model. Ook hier hebben we in de voorbewerkingen gezorgd dat de concentraties uit SOBEK naar de watervlakkenkaart konden worden geïnterpoleerd.

Het risicogetal van deze maatlat wordt berekend op basis van lineaire interpolatie tussen de volgende twee getalsparen:

* 0 mg/l: risicogetal 0
* 1.5 mg/l: risicogetal 1

Net als bij stikstof hanteren we als wegingsfactor voor deze maatlat de waarde 0.5.

### Maximale hoeveelheid biomassa

De hoeveelheid biomassa die een waterlichaam kan opnemen is een functie van de waterdiepte. Daarom passen we voor deze maatlat een transformatiefunctie toe op de waterdiepte van het waterlichaam. De formule voor deze transformatie luidt:

maximale biomassa = 1683.6*EXP(-0.578*watediepte)

Vervolgens berekenen we het risicogetal middels lineaire interpolatie tussen de volgende twee getalsparen:

* 0: risicogetal 0
* 1400: risicogetal 1

Als wegingsfactor nemen we 1.

## Weging

Samenvattend berekenen we de risicofactor 'biomassa' op basis van de volgende maatlatten en hun wegingsfactoren:

* Overschrijdingstemperatuur: wegingsfactor 1
* Vermesting stikstof: wegingsfactor 0.5
* Vermesting fosfor: wegingsfactor 0.5
* Maximale biomassa: wegingsfactor 1


