
project:
  type: website

website:
  title: "Klimaatatlas"
  navbar:
    left:
      - index.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Tutorial"
        contents:
          - Tutorial/tutorial.qmd
      - section: "Gebruikershandleiding"
        contents:
          - GUI/structure.qmd
          - GUI/workings.qmd
          - GUI/general.qmd
          - GUI/models.qmd
          - GUI/seizoenen.qmd
          - GUI/volume.qmd
          - GUI/patterns.qmd
          - GUI/extra.qmd
      - section: "Technische documentatie"
        contents:
          - GUI/structure.qmd
      - section: "Voorbewerkingen"
        contents:
          - GUI/structure.qmd
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



